name: Development

on:
  pull_request:
    branches: [uat]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.base.ref == 'uat' &&
      (
        contains(
          fromJson(github.event.pull_request.reviews).map(review => review.user.login),
          'harishvgts'
        ) ||
        contains(
          fromJson(github.event.pull_request.reviews).map(review => review.user.login),
          'nandavgts'
        )
      )

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          path: 'dev'
