name: Development

on:
  push:
    branches: uat

jobs:
  build:
    if: github.event.pull_request.base.ref == 'uat' && github.event.review.state == 'APPROVED' && github.event.review.user.login == 'sarathvgts' || github.event.review.user.login == 'nandavgts'
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4  
        with:
          path: 'dev'
