name: Development

on:
  pull_request:
    branches: [uat]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          path: 'dev'

      - name: Check Approval
        id: check_approval
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "uat" && "${{ github.event.review.state }}" == "approved" && ("${{ github.event.review.user.login }}" == "harishvgts" || "${{ github.event.review.user.login }}" == "nandavgts") ]]; then
            echo "approved_by=true" >> $GITHUB_ENV
          else
            echo "approved_by=false" >> $GITHUB_ENV
          fi
