name: Development

on:
  push:
    branches: [uat]

env: 
  APP_NAME: test
  APP_ENV: dev
  APP_DIR: /www/data
  ASSIGNED_APPROVER: ${{ secrets.ASSIGNED_APPROVER }}

jobs:
  build:
    if: github.event.pull_request.base.ref == 'uat' && github.event.pull_request.user.login == env.ASSIGNED_APPROVER
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4  
        with:
          path: 'dev'
