name: Development

on:
  push:
    branches: uat

env:
  APP_NAME: test
  APP_ENV: dev
  APP_DIR: /www/data

jobs:
  build:
    if: github.event.pull_request.base.ref == 'uat' && github.event.review.state == 'approved' && github.event.review.user.login == secrets.ASSIGNED_APPROVER
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4  
        with:
          path: 'dev'
