name: Development

on:
  pull_request_review:
    types: [submitted]
    branches: [uat]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR review
        id: check_review
        if: ${{ github.event.review.state == 'approved' && (github.event.review.user.login == 'harishvgts' || github.event.review.user.login == 'nandavgts') }}
        run: echo "approved_by=true" >> $GITHUB_ENV

      - name: Set default approval state
        if: steps.check_review.outcome != 'success'
        run: echo "approved_by=false" >> $GITHUB_ENV

      - name: Fail if not approved
        if: env.approved_by == 'false'
        run: |
          echo "PR not approved by the specified users. Stopping the build."
          exit 1

      - name: Use the approved_by output
        if: env.approved_by == 'true'
        run: echo "Was the PR approved by the specified users? ${{ env.approved_by }}"
