name: Development

on:
  pull_request:
    branches: [uat]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: 'dev'

      - name: Check Pull Request Approval
        id: check_approval
        run: |
          PR_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews"
          APPROVALS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$PR_URL")

          # Check if harishvgts has approved
          if echo "$APPROVALS" | jq -e '.[] | select(.user.login == "harishvgts" and .state == "APPROVED")' > /dev/null; then
            echo "harishvgts has approved"
          # Check if nandavgts has approved
          elif echo "$APPROVALS" | jq -e '.[] | select(.user.login == "nandavgts" and .state == "APPROVED")' > /dev/null; then
            echo "nandavgts has approved"
          else
            echo "No required approvers found"
            exit 1
          fi

      - name: Proceed with Build
        run: |
          echo "Approvals are in place. Proceeding with build..."
