name: Development

on:
  pull_request:
    branches: [uat]

jobs:
  check_approvals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: 'dev'

      - name: Check Pull Request Approval
        id: check_approval
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const approved = reviews.some(review => 
              (review.user.login === 'harishvgts' || review.user.login === 'nandavgts') && 
              review.state === 'APPROVED'
            );

            if (!approved) {
              core.setFailed('Required approvers have not approved the pull request.');
            }

  build:
    needs: check_approvals
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: 'dev'

      - name: Proceed with Build
        run: |
          echo "Approvals are in place. Proceeding with build..."
