name: Development

on:
  pull_request_review:
    types: [submitted]
    branches: [uat]
jobs:
  check-review:
    runs-on: ubuntu-latest
    outputs:
      approved_by: ${{ steps.check_review.outputs.approved_by }}
    steps:
      - name: Check PR review
        id: check_review
        run: |
          if [[ "${{ github.event.review.state }}" == "approved" && ("${{ github.event.review.user.login }}" == "vasanthvgts" || "${{ github.event.review.user.login }}" == "nandavgts") ]]; then
            echo "approved_by=true" >> $GITHUB_ENV
            echo "::set-output name=approved_by::true"
          else
            echo "approved_by=false" >> $GITHUB_ENV
            echo "::set-output name=approved_by::false"
          fi
          
      - name: Fail if not approved
        run: |
          if [[ "${{ steps.check_review.outputs.approved_by }}" == "false" ]]; then
            echo "This PR cannot be merged until it is approved by the assigned approvers."
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-review
    if: needs.check-review.outputs.approved_by == 'true'
    steps:
      - name: Run build
        run: echo "Build process starts..."
