name: Development

on:
  pull_request_review:
    types: [submitted]
    branches: [uat]

jobs:
  check_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR review
        id: check_review
        if: ${{ github.event.review.state == 'approved' && (github.event.review.user.login == 'harishvgts' || github.event.review.user.login == 'nandavgts') }}
        run: echo "approved_by=true" >> $GITHUB_ENV

      - name: Set default approval state
        if: steps.check_review.outcome != 'success'
        run: echo "approved_by=false" >> $GITHUB_ENV

      - name: Use the approved_by output
        run: echo "Was the PR approved by the specified users? ${{ env.approved_by }}"

  build:
    needs: check_approvals
    if: env.approved_by == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Proceed with Build
        run: |
          echo "Approvals are in place. Proceeding with build..."
