name: Development

on:
  pull_request:
    branches: [uat]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'uat' && github.event.pull_request.review.state == 'approved' && github.event.pull_request.review.user.login == 'harishvgts' }}

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          path: 'dev'
