name: Development

on:
  pull_request:
    types: [review_requested, review_request_removed, submitted]

env:
  APP_NAME: test
  APP_ENV: dev
  APP_DIR: /www/data
  ASSIGNED_APPROVER: ${{ secrets.ASSIGNED_APPROVER }}

jobs:
  build:
    if: >
      github.event.pull_request.base.ref == 'uat' &&
      (
        (github.event_name == 'pull_request' &&
        github.event.review.state == 'approved' &&
        github.event.review.user.login == env.ASSIGNED_APPROVER) ||
        (github.event_name == 'pull_request_review' &&
        github.event.review.user.login == env.ASSIGNED_APPROVER && 
        github.event.review.state == 'approved')
      )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: 'dev'
