name: Development

on:
  pull_request:
    branches: [uat]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: 'dev'

      - name: Check Pull Request Approval
        id: check_approval
        run: |
          PR_URL="${{ github.event.pull_request.url }}"
          APPROVALS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${PR_URL}/reviews")
          if echo "$APPROVALS" | grep -q '"user": { "login": "harishvgts" }'; then
            echo "harishvgts has approved"
          elif echo "$APPROVALS" | grep -q '"user": { "login": "nandavgts" }'; then
            echo "nandavgts has approved"
          else
            echo "No required approvers found"
            exit 1
          fi

      - name: Proceed with Build
        run: |
          echo "Approvals are in place. Proceeding with build..."
